import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

type Verdict='true_positive'|'false_positive'; type Severity='critical'|'high'|'medium'|'low'|string;
type Finding={file:string;category:string;score?:number;threshold?:number;verdict?:Verdict};
type Verified={sourceReport?:{generatedAt?:string;thresholds?:Record<string,number>};findings:Finding[]};
type BaselineFinding={file:string;category:string;severity?:Severity;problem?:string}; type Baseline={findings:BaselineFinding[]};
type Report={generatedAt?:string;files:{file:string;scores:Record<string,number>}[];thresholds:Record<string,number>};
const root=path.resolve(process.argv[2]??'.'); const dir=path.join(root,'.jev-review');
const report:Report=JSON.parse(await readFile(path.join(dir,'report.json'),'utf8')); const verified:Verified=JSON.parse(await readFile(path.join(dir,'verified-report.json'),'utf8')); const baseline:Baseline=JSON.parse(await readFile(path.join(dir,'baseline-report.json'),'utf8'));
const flaggedFiles=new Set(report.files.filter(f=>Object.entries(f.scores).some(([c,s])=>s>=(report.thresholds[c]??1))).map(f=>f.file));
const retained=baseline.findings.filter(f=>flaggedFiles.has(f.file)); const missed=baseline.findings.filter(f=>!flaggedFiles.has(f.file)); const baselineFiles=new Set(baseline.findings.map(f=>f.file));
const verifiedTp=verified.findings.filter(f=>f.verdict==='true_positive').length; const verifiedFp=verified.findings.filter(f=>f.verdict==='false_positive').length;
const totalFiles=report.files.length; const selectedFiles=flaggedFiles.size; const fileReduction=totalFiles?1-selectedFiles/totalFiles:0; const issueRetention=baseline.findings.length?retained.length/baseline.findings.length:1;
const important=(f:BaselineFinding)=>['critical','high','medium'].includes((f.severity??'').toLowerCase()); const importantAll=baseline.findings.filter(important); const importantRetained=retained.filter(important); const importantMissed=missed.filter(important); const importantRetention=importantAll.length?importantRetained.length/importantAll.length:1;
const thresholdMismatch=verified.findings.filter(f=>f.threshold!==undefined&&report.thresholds[f.category]!==undefined&&Math.abs(f.threshold-report.thresholds[f.category])>1e-9).length; const sourceTimestampMismatch=Boolean(verified.sourceReport?.generatedAt&&report.generatedAt&&verified.sourceReport.generatedAt!==report.generatedAt); const consistency={ok:thresholdMismatch===0&&!sourceTimestampMismatch,thresholdMismatches:thresholdMismatch,sourceReportTimestampMatches:!sourceTimestampMismatch,warnings:[] as string[]}; if(thresholdMismatch)consistency.warnings.push(`${thresholdMismatch} verified finding(s) use thresholds different from report.json.`); if(sourceTimestampMismatch)consistency.warnings.push('verified-report.json references a different report.json generation timestamp; regenerate verification before trusting precision.');
const result={generatedAt:new Date().toISOString(),consistency,files:{total:totalFiles,selected:selectedFiles,reduction:fileReduction},triage:{verifiedTruePositives:verifiedTp,verifiedFalsePositives:verifiedFp,precision:verifiedTp+verifiedFp?verifiedTp/(verifiedTp+verifiedFp):null},baseline:{issues:baseline.findings.length,filesWithIssues:baselineFiles.size,retainedIssues:retained.length,missedIssues:missed.length,issueRetention,mediumOrHigher:{issues:importantAll.length,retained:importantRetained.length,missed:importantMissed.length,retention:importantRetention}},costProxy:{description:'File-count proxy only; replace with measured tokens/cost when available.',fullReviewUnits:totalFiles,jevSecondPassUnits:selectedFiles,secondPassReduction:fileReduction},missed};
await mkdir(dir,{recursive:true}); await writeFile(path.join(dir,'evaluation.json'),JSON.stringify(result,null,2)+'\n'); const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
console.log(`Files sent to deep review: ${selectedFiles}/${totalFiles} (${pct(1-fileReduction)})`); console.log(`Deep-review file reduction: ${pct(fileReduction)}`); console.log(`Verified triage precision: ${result.triage.precision===null?'n/a':pct(result.triage.precision)}`); console.log(`Baseline issues retained: ${retained.length}/${baseline.findings.length} (${pct(issueRetention)})`); console.log(`Medium+ issues retained: ${importantRetained.length}/${importantAll.length} (${pct(importantRetention)})`); console.log(`Baseline issues missed: ${missed.length}`); if(!consistency.ok) for(const warning of consistency.warnings) console.warn(`WARNING: ${warning}`); console.log('Evaluation: .jev-review/evaluation.json');
