import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { globby } from 'globby';

const DEFAULT_EXTENSIONS=['js','jsx','mjs','cjs','ts','tsx','mts','cts','py','php','rb','go','rs','java','kt','kts','cs','vue','svelte','astro','css','scss','sql','sh','patch','diff'];
const IGNORE=['**/node_modules/**','**/.git/**','**/dist/**','**/build/**','**/.next/**','**/.nuxt/**','**/.output/**','**/coverage/**','**/vendor/**','**/.venv/**','**/venv/**','**/.jev-review/**','**/*.min.js','**/*.map'];
export async function collectFiles(root:string):Promise<string[]>{return globby(`**/*.{${DEFAULT_EXTENSIONS.join(',')}}`,{cwd:root,absolute:true,onlyFiles:true,unique:true,dot:false,ignore:IGNORE,gitignore:true});}
export async function readSource(file:string):Promise<string>{return readFile(file,'utf8');}
export function relativeFile(root:string,file:string):string{return path.relative(root,file).split(path.sep).join('/');}
export function isPatchFile(file:string):boolean{return /\.(patch|diff)$/i.test(file);}
export interface SourceChunk{index:number;total:number;startLine:number;endLine:number;content:string;kind:'source'|'diff';}
type Part={startLine:number;endLine:number;content:string};type DiffPart=Part&{fileId:string};

export function chunkSource(file:string,text:string,maxChars=24_000):SourceChunk[]{const diff=isPatchFile(file);const parts=diff?splitDiff(text,maxChars):splitLines(text,maxChars);return parts.map((p,index)=>({index,total:parts.length,...p,kind:diff?'diff':'source'}));}
function splitLines(text:string,maxChars:number):Part[]{const lines=text.split('\n');const out:Part[]=[];let start=1,buf:string[]=[],chars=0,lineNo=1;const flush=()=>{if(!buf.length)return;out.push({startLine:start,endLine:start+buf.length-1,content:buf.join('\n')});buf=[];chars=0;};for(const line of lines){const size=line.length+1;if(buf.length&&chars+size>maxChars){flush();start=lineNo;}if(!buf.length&&size>maxChars){for(let i=0;i<line.length;i+=maxChars)out.push({startLine:lineNo,endLine:lineNo,content:line.slice(i,i+maxChars)});start=lineNo+1;lineNo++;continue;}if(!buf.length)start=lineNo;buf.push(line);chars+=size;lineNo++;}flush();return out.length?out:[{startLine:1,endLine:1,content:''}];}

/** Parse diff hunks and only pack adjacent hunks that belong to the same changed file. */
function splitDiff(text:string,maxChars:number):Part[]{const lines=text.split('\n'),units:DiffPart[]=[];let fileHeader:string[]=[],fileId='__preamble__',unit:string[]=[],unitStart=1,lineNo=1;const emit=()=>{if(!unit.length)return;units.push({fileId,startLine:unitStart,endLine:lineNo-1,content:[...fileHeader,...unit].join('\n')});unit=[];};for(const line of lines){if(line.startsWith('diff --git ')){emit();fileId=line;fileHeader=[line];unitStart=lineNo;}else if(line.startsWith('@@ ')){emit();unitStart=lineNo;unit=[line];}else if(unit.length)unit.push(line);else fileHeader.push(line);lineNo++;}emit();if(!units.length)return splitLines(text,maxChars);const normalized:DiffPart[]=[];for(const u of units){if(u.content.length<=maxChars)normalized.push(u);else normalized.push(...splitLines(u.content,maxChars).map(p=>({fileId:u.fileId,startLine:u.startLine+p.startLine-1,endLine:u.startLine+p.endLine-1,content:p.content})));}const packed:DiffPart[]=[];let current:DiffPart|null=null;for(const u of normalized){if(current&&current.fileId===u.fileId&&current.content.length+u.content.length+2<=maxChars)current={fileId:current.fileId,startLine:current.startLine,endLine:u.endLine,content:`${current.content}\n\n${u.content}`};else{if(current)packed.push(current);current=u;}}if(current)packed.push(current);return packed.map(({startLine,endLine,content})=>({startLine,endLine,content}));}
